/*----------------------------------------------------------------------
 * This file is generated by mk_parser.py.
 *----------------------------------------------------------------------*/
#include <assert.h>
#include <stdint.h>
#include <stdio.h>
#include "cparser.h"
#include "cparser_priv.h"
#include "cparser_token.h"
#include "cparser_tree.h"

cparser_result_t
cparser_glue_rd_filename_offset_nbytes_dohex(cparser_t *parser)
{
    char *filename_val;
    char **filename_ptr = NULL;
    uint32_t offset_val;
    uint32_t *offset_ptr = NULL;
    uint32_t nbytes_val;
    uint32_t *nbytes_ptr = NULL;
    char *dohex_val;
    char **dohex_ptr = NULL;
    cparser_result_t rc;

    rc = cparser_get_string(&parser->tokens[1], &filename_val);
    assert(CPARSER_OK == rc);
    filename_ptr = &filename_val;
    rc = cparser_get_uint(&parser->tokens[2], &offset_val);
    assert(CPARSER_OK == rc);
    offset_ptr = &offset_val;
    rc = cparser_get_uint(&parser->tokens[3], &nbytes_val);
    assert(CPARSER_OK == rc);
    nbytes_ptr = &nbytes_val;
    rc = cparser_get_string(&parser->tokens[4], &dohex_val);
    if (CPARSER_OK == rc)
    {
        dohex_ptr = &dohex_val;
    }
    else
    {
        assert(5 > parser->token_tos);
    }
    cparser_cmd_rd_filename_offset_nbytes_dohex(&parser->context,
                                                filename_ptr,
                                                offset_ptr,
                                                nbytes_ptr,
                                                dohex_ptr);
    return CPARSER_OK;
}

cparser_result_t
cparser_glue_wd_filename_offset_nbytes(cparser_t *parser)
{
    char *filename_val;
    char **filename_ptr = NULL;
    uint32_t offset_val;
    uint32_t *offset_ptr = NULL;
    uint32_t nbytes_val;
    uint32_t *nbytes_ptr = NULL;
    cparser_result_t rc;

    rc = cparser_get_string(&parser->tokens[1], &filename_val);
    assert(CPARSER_OK == rc);
    filename_ptr = &filename_val;
    rc = cparser_get_uint(&parser->tokens[2], &offset_val);
    assert(CPARSER_OK == rc);
    offset_ptr = &offset_val;
    rc = cparser_get_uint(&parser->tokens[3], &nbytes_val);
    assert(CPARSER_OK == rc);
    nbytes_ptr = &nbytes_val;
    cparser_cmd_wd_filename_offset_nbytes(&parser->context,
                                          filename_ptr,
                                          offset_ptr,
                                          nbytes_ptr);
    return CPARSER_OK;
}

cparser_result_t
cparser_glue_curr_filename(cparser_t *parser)
{
    char *filename_val;
    char **filename_ptr = NULL;
    cparser_result_t rc;

    rc = cparser_get_string(&parser->tokens[1], &filename_val);
    assert(CPARSER_OK == rc);
    filename_ptr = &filename_val;
    cparser_cmd_curr_filename(&parser->context,
                              filename_ptr);
    return CPARSER_OK;
}

cparser_result_t
cparser_glue_ru_offset_nbytes_dohex(cparser_t *parser)
{
    uint32_t offset_val;
    uint32_t *offset_ptr = NULL;
    uint32_t nbytes_val;
    uint32_t *nbytes_ptr = NULL;
    char *dohex_val;
    char **dohex_ptr = NULL;
    cparser_result_t rc;

    rc = cparser_get_uint(&parser->tokens[1], &offset_val);
    assert(CPARSER_OK == rc);
    offset_ptr = &offset_val;
    rc = cparser_get_uint(&parser->tokens[2], &nbytes_val);
    assert(CPARSER_OK == rc);
    nbytes_ptr = &nbytes_val;
    rc = cparser_get_string(&parser->tokens[3], &dohex_val);
    if (CPARSER_OK == rc)
    {
        dohex_ptr = &dohex_val;
    }
    else
    {
        assert(4 > parser->token_tos);
    }
    cparser_cmd_ru_offset_nbytes_dohex(&parser->context,
                                       offset_ptr,
                                       nbytes_ptr,
                                       dohex_ptr);
    return CPARSER_OK;
}

cparser_result_t
cparser_glue_wu_offset_nbytes(cparser_t *parser)
{
    uint32_t offset_val;
    uint32_t *offset_ptr = NULL;
    uint32_t nbytes_val;
    uint32_t *nbytes_ptr = NULL;
    cparser_result_t rc;

    rc = cparser_get_uint(&parser->tokens[1], &offset_val);
    assert(CPARSER_OK == rc);
    offset_ptr = &offset_val;
    rc = cparser_get_uint(&parser->tokens[2], &nbytes_val);
    assert(CPARSER_OK == rc);
    nbytes_ptr = &nbytes_val;
    cparser_cmd_wu_offset_nbytes(&parser->context,
                                 offset_ptr,
                                 nbytes_ptr);
    return CPARSER_OK;
}

cparser_result_t
cparser_glue_rf_offset_nbytes_dohex(cparser_t *parser)
{
    uint32_t offset_val;
    uint32_t *offset_ptr = NULL;
    uint32_t nbytes_val;
    uint32_t *nbytes_ptr = NULL;
    char *dohex_val;
    char **dohex_ptr = NULL;
    cparser_result_t rc;

    rc = cparser_get_uint(&parser->tokens[1], &offset_val);
    assert(CPARSER_OK == rc);
    offset_ptr = &offset_val;
    rc = cparser_get_uint(&parser->tokens[2], &nbytes_val);
    assert(CPARSER_OK == rc);
    nbytes_ptr = &nbytes_val;
    rc = cparser_get_string(&parser->tokens[3], &dohex_val);
    if (CPARSER_OK == rc)
    {
        dohex_ptr = &dohex_val;
    }
    else
    {
        assert(4 > parser->token_tos);
    }
    cparser_cmd_rf_offset_nbytes_dohex(&parser->context,
                                       offset_ptr,
                                       nbytes_ptr,
                                       dohex_ptr);
    return CPARSER_OK;
}

cparser_result_t
cparser_glue_wf_offset_nbytes(cparser_t *parser)
{
    uint32_t offset_val;
    uint32_t *offset_ptr = NULL;
    uint32_t nbytes_val;
    uint32_t *nbytes_ptr = NULL;
    cparser_result_t rc;

    rc = cparser_get_uint(&parser->tokens[1], &offset_val);
    assert(CPARSER_OK == rc);
    offset_ptr = &offset_val;
    rc = cparser_get_uint(&parser->tokens[2], &nbytes_val);
    assert(CPARSER_OK == rc);
    nbytes_ptr = &nbytes_val;
    cparser_cmd_wf_offset_nbytes(&parser->context,
                                 offset_ptr,
                                 nbytes_ptr);
    return CPARSER_OK;
}

cparser_result_t
cparser_glue_smap_high_base(cparser_t *parser)
{
    uint32_t high_val;
    uint32_t *high_ptr = NULL;
    uint32_t base_val;
    uint32_t *base_ptr = NULL;
    cparser_result_t rc;

    rc = cparser_get_uint(&parser->tokens[1], &high_val);
    assert(CPARSER_OK == rc);
    high_ptr = &high_val;
    rc = cparser_get_uint(&parser->tokens[2], &base_val);
    assert(CPARSER_OK == rc);
    base_ptr = &base_val;
    cparser_cmd_smap_high_base(&parser->context,
                               high_ptr,
                               base_ptr);
    return CPARSER_OK;
}

cparser_result_t
cparser_glue_map_kaddr(cparser_t *parser)
{
    uint32_t kaddr_val;
    uint32_t *kaddr_ptr = NULL;
    cparser_result_t rc;

    rc = cparser_get_uint(&parser->tokens[1], &kaddr_val);
    assert(CPARSER_OK == rc);
    kaddr_ptr = &kaddr_val;
    cparser_cmd_map_kaddr(&parser->context,
                          kaddr_ptr);
    return CPARSER_OK;
}

cparser_result_t
cparser_glue_help_filter(cparser_t *parser)
{
    char *filter_val;
    char **filter_ptr = NULL;
    cparser_result_t rc;

    rc = cparser_get_string(&parser->tokens[1], &filter_val);
    if (CPARSER_OK == rc)
    {
        filter_ptr = &filter_val;
    }
    else
    {
        assert(2 > parser->token_tos);
    }
    cparser_cmd_help_filter(&parser->context,
                            filter_ptr);
    return CPARSER_OK;
}

cparser_result_t
cparser_glue_exit(cparser_t *parser)
{
    cparser_cmd_exit(&parser->context);
    return CPARSER_OK;
}

cparser_node_t cparser_node_exit_eol = {
    CPARSER_NODE_END,
    0,
    cparser_glue_exit,
    "Exit",
    NULL,
    NULL};

cparser_node_t cparser_node_exit = {
    CPARSER_NODE_KEYWORD,
    0,
    "exit",
    NULL,
    NULL,
    &cparser_node_exit_eol};

cparser_node_t cparser_node_help_filter_eol = {
    CPARSER_NODE_END,
    0,
    cparser_glue_help_filter,
    "Help",
    NULL,
    NULL};

cparser_node_t cparser_node_help_filter = {
    CPARSER_NODE_STRING,
    CPARSER_NODE_FLAGS_OPT_START | CPARSER_NODE_FLAGS_OPT_END,
    "<STRING:filter>",
    NULL,
    NULL,
    &cparser_node_help_filter_eol};

cparser_node_t cparser_node_help_eol = {
    CPARSER_NODE_END,
    CPARSER_NODE_FLAGS_OPT_PARTIAL,
    cparser_glue_help_filter,
    NULL,
    &cparser_node_help_filter,
    NULL};

cparser_node_t cparser_node_help = {
    CPARSER_NODE_KEYWORD,
    0,
    "help",
    NULL,
    &cparser_node_exit,
    &cparser_node_help_eol};

cparser_node_t cparser_node_map_kaddr_eol = {
    CPARSER_NODE_END,
    0,
    cparser_glue_map_kaddr,
    "Map a kernel address to the PDT set with `smap`",
    NULL,
    NULL};

cparser_node_t cparser_node_map_kaddr = {
    CPARSER_NODE_UINT,
    0,
    "<UINT:kaddr>",
    NULL,
    NULL,
    &cparser_node_map_kaddr_eol};

cparser_node_t cparser_node_map = {
    CPARSER_NODE_KEYWORD,
    0,
    "map",
    NULL,
    &cparser_node_help,
    &cparser_node_map_kaddr};

cparser_node_t cparser_node_smap_high_base_eol = {
    CPARSER_NODE_END,
    0,
    cparser_glue_smap_high_base,
    "Set variables for map",
    NULL,
    NULL};

cparser_node_t cparser_node_smap_high_base = {
    CPARSER_NODE_UINT,
    0,
    "<UINT:base>",
    NULL,
    NULL,
    &cparser_node_smap_high_base_eol};

cparser_node_t cparser_node_smap_high = {
    CPARSER_NODE_UINT,
    0,
    "<UINT:high>",
    NULL,
    NULL,
    &cparser_node_smap_high_base};

cparser_node_t cparser_node_smap = {
    CPARSER_NODE_KEYWORD,
    0,
    "smap",
    NULL,
    &cparser_node_map,
    &cparser_node_smap_high};

cparser_node_t cparser_node_wf_offset_nbytes_eol = {
    CPARSER_NODE_END,
    0,
    cparser_glue_wf_offset_nbytes,
    "Write to fd=3 at `offset` `nbytes` bytes.",
    NULL,
    NULL};

cparser_node_t cparser_node_wf_offset_nbytes = {
    CPARSER_NODE_UINT,
    0,
    "<UINT:nbytes>",
    NULL,
    NULL,
    &cparser_node_wf_offset_nbytes_eol};

cparser_node_t cparser_node_wf_offset = {
    CPARSER_NODE_UINT,
    0,
    "<UINT:offset>",
    NULL,
    NULL,
    &cparser_node_wf_offset_nbytes};

cparser_node_t cparser_node_wf = {
    CPARSER_NODE_KEYWORD,
    0,
    "wf",
    NULL,
    &cparser_node_smap,
    &cparser_node_wf_offset};

cparser_node_t cparser_node_rf_offset_nbytes_dohex_eol = {
    CPARSER_NODE_END,
    0,
    cparser_glue_rf_offset_nbytes_dohex,
    "Read from fd=3 at `offset` `nbytes` bytes.  Set `dohex` to 'h' to preform a hexdump, otherwise prints raw data. ",
    NULL,
    NULL};

cparser_node_t cparser_node_rf_offset_nbytes_dohex = {
    CPARSER_NODE_STRING,
    CPARSER_NODE_FLAGS_OPT_START | CPARSER_NODE_FLAGS_OPT_END,
    "<STRING:dohex>",
    NULL,
    NULL,
    &cparser_node_rf_offset_nbytes_dohex_eol};

cparser_node_t cparser_node_rf_offset_nbytes_eol = {
    CPARSER_NODE_END,
    CPARSER_NODE_FLAGS_OPT_PARTIAL,
    cparser_glue_rf_offset_nbytes_dohex,
    NULL,
    &cparser_node_rf_offset_nbytes_dohex,
    NULL};

cparser_node_t cparser_node_rf_offset_nbytes = {
    CPARSER_NODE_UINT,
    0,
    "<UINT:nbytes>",
    NULL,
    NULL,
    &cparser_node_rf_offset_nbytes_eol};

cparser_node_t cparser_node_rf_offset = {
    CPARSER_NODE_UINT,
    0,
    "<UINT:offset>",
    NULL,
    NULL,
    &cparser_node_rf_offset_nbytes};

cparser_node_t cparser_node_rf = {
    CPARSER_NODE_KEYWORD,
    0,
    "rf",
    NULL,
    &cparser_node_wf,
    &cparser_node_rf_offset};

cparser_node_t cparser_node_wu_offset_nbytes_eol = {
    CPARSER_NODE_END,
    0,
    cparser_glue_wu_offset_nbytes,
    "Write to VA at `offset` `nbytes` bytes.",
    NULL,
    NULL};

cparser_node_t cparser_node_wu_offset_nbytes = {
    CPARSER_NODE_UINT,
    0,
    "<UINT:nbytes>",
    NULL,
    NULL,
    &cparser_node_wu_offset_nbytes_eol};

cparser_node_t cparser_node_wu_offset = {
    CPARSER_NODE_UINT,
    0,
    "<UINT:offset>",
    NULL,
    NULL,
    &cparser_node_wu_offset_nbytes};

cparser_node_t cparser_node_wu = {
    CPARSER_NODE_KEYWORD,
    0,
    "wu",
    NULL,
    &cparser_node_rf,
    &cparser_node_wu_offset};

cparser_node_t cparser_node_ru_offset_nbytes_dohex_eol = {
    CPARSER_NODE_END,
    0,
    cparser_glue_ru_offset_nbytes_dohex,
    "Read from VA at `offset` `nbytes` bytes.  Set `dohex` to 'h' to preform a hexdump, otherwise prints raw data. ",
    NULL,
    NULL};

cparser_node_t cparser_node_ru_offset_nbytes_dohex = {
    CPARSER_NODE_STRING,
    CPARSER_NODE_FLAGS_OPT_START | CPARSER_NODE_FLAGS_OPT_END,
    "<STRING:dohex>",
    NULL,
    NULL,
    &cparser_node_ru_offset_nbytes_dohex_eol};

cparser_node_t cparser_node_ru_offset_nbytes_eol = {
    CPARSER_NODE_END,
    CPARSER_NODE_FLAGS_OPT_PARTIAL,
    cparser_glue_ru_offset_nbytes_dohex,
    NULL,
    &cparser_node_ru_offset_nbytes_dohex,
    NULL};

cparser_node_t cparser_node_ru_offset_nbytes = {
    CPARSER_NODE_UINT,
    0,
    "<UINT:nbytes>",
    NULL,
    NULL,
    &cparser_node_ru_offset_nbytes_eol};

cparser_node_t cparser_node_ru_offset = {
    CPARSER_NODE_UINT,
    0,
    "<UINT:offset>",
    NULL,
    NULL,
    &cparser_node_ru_offset_nbytes};

cparser_node_t cparser_node_ru = {
    CPARSER_NODE_KEYWORD,
    0,
    "ru",
    NULL,
    &cparser_node_wu,
    &cparser_node_ru_offset};

cparser_node_t cparser_node_curr_filename_eol = {
    CPARSER_NODE_END,
    0,
    cparser_glue_curr_filename,
    "Get current task struct address using the driver at `filename`",
    NULL,
    NULL};

cparser_node_t cparser_node_curr_filename = {
    CPARSER_NODE_STRING,
    0,
    "<STRING:filename>",
    NULL,
    NULL,
    &cparser_node_curr_filename_eol};

cparser_node_t cparser_node_curr = {
    CPARSER_NODE_KEYWORD,
    0,
    "curr",
    NULL,
    &cparser_node_ru,
    &cparser_node_curr_filename};

cparser_node_t cparser_node_wd_filename_offset_nbytes_eol = {
    CPARSER_NODE_END,
    0,
    cparser_glue_wd_filename_offset_nbytes,
    "Write to kernel memory using the driver at `filename` `nbytes` bytes to `offset`.",
    NULL,
    NULL};

cparser_node_t cparser_node_wd_filename_offset_nbytes = {
    CPARSER_NODE_UINT,
    0,
    "<UINT:nbytes>",
    NULL,
    NULL,
    &cparser_node_wd_filename_offset_nbytes_eol};

cparser_node_t cparser_node_wd_filename_offset = {
    CPARSER_NODE_UINT,
    0,
    "<UINT:offset>",
    NULL,
    NULL,
    &cparser_node_wd_filename_offset_nbytes};

cparser_node_t cparser_node_wd_filename = {
    CPARSER_NODE_STRING,
    0,
    "<STRING:filename>",
    NULL,
    NULL,
    &cparser_node_wd_filename_offset};

cparser_node_t cparser_node_wd = {
    CPARSER_NODE_KEYWORD,
    0,
    "wd",
    NULL,
    &cparser_node_curr,
    &cparser_node_wd_filename};

cparser_node_t cparser_node_rd_filename_offset_nbytes_dohex_eol = {
    CPARSER_NODE_END,
    0,
    cparser_glue_rd_filename_offset_nbytes_dohex,
    "Read from kernel memory using the driver at `filename` `nbytes` bytes from `offset`. Set `dohex` to 'h' to preform a hexdump, otherwise prints raw data. ",
    NULL,
    NULL};

cparser_node_t cparser_node_rd_filename_offset_nbytes_dohex = {
    CPARSER_NODE_STRING,
    CPARSER_NODE_FLAGS_OPT_START | CPARSER_NODE_FLAGS_OPT_END,
    "<STRING:dohex>",
    NULL,
    NULL,
    &cparser_node_rd_filename_offset_nbytes_dohex_eol};

cparser_node_t cparser_node_rd_filename_offset_nbytes_eol = {
    CPARSER_NODE_END,
    CPARSER_NODE_FLAGS_OPT_PARTIAL,
    cparser_glue_rd_filename_offset_nbytes_dohex,
    NULL,
    &cparser_node_rd_filename_offset_nbytes_dohex,
    NULL};

cparser_node_t cparser_node_rd_filename_offset_nbytes = {
    CPARSER_NODE_UINT,
    0,
    "<UINT:nbytes>",
    NULL,
    NULL,
    &cparser_node_rd_filename_offset_nbytes_eol};

cparser_node_t cparser_node_rd_filename_offset = {
    CPARSER_NODE_UINT,
    0,
    "<UINT:offset>",
    NULL,
    NULL,
    &cparser_node_rd_filename_offset_nbytes};

cparser_node_t cparser_node_rd_filename = {
    CPARSER_NODE_STRING,
    0,
    "<STRING:filename>",
    NULL,
    NULL,
    &cparser_node_rd_filename_offset};

cparser_node_t cparser_node_rd = {
    CPARSER_NODE_KEYWORD,
    0,
    "rd",
    NULL,
    &cparser_node_wd,
    &cparser_node_rd_filename};

cparser_node_t cparser_root = {
    CPARSER_NODE_ROOT,
    0,
    NULL,
    "Root node of the parser tree",
    NULL,
    &cparser_node_rd};
